### installing numpy using "pip install numpy"
        import numpy using "import numpy as np"

#### Numpy ndarray
    - homogeneous because virtually all the items in it are of the same type and the same size
    - Size is fixed. reamins same as we create at the begining unlike python list which grow or shrink
    - Main functions
      - array  a = np.array([1,2,3])
      - array can be assigned mixture of tuples and list
        - e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)]) 
      - a.shape     # defines size like 2*2
      - a.dtype         # define type int float char
      - a.ndim       # attribute for getting the axes
      - a.size        # determine the array length
      - a.itemsize      # defines the size in bytes of each item

In [139]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
print(f"type = {array.dtype}, itemsize = {array.itemsize} \n\
shape = {array.shape}, axis = {array.ndim}, length = {array.size}")


type = int64, itemsize = 8 
shape = (2, 3), axis = 2, length = 6


#### ndarray options and creation
    - add dtype using dtype in array function
      - f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
    - np.zeros((3, 3))   # create array with all 0  3* 3 matrix
    - np.ones((3, 3))
    - np.arange(4, 10)   # create array [4,5,6,7,8,9]
      - third arrgument will add for gap
      - np.arange(0, 12, 3)    # create array array([0, 3, 6, 9])
      - use reshape with arrange to define shape
      - np.arange(0, 12).reshape(3, 4)
    - np.linspace(0,10,5)  # first two arguments the initial and end values of the sequence, but the third argument, i defines the number of elements into which you want the interval to be split. 
    - np.random.random((3,3))    # generate random number

In [140]:
complex_array = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
print(f"Complex array  = \n{complex_array}")

ones_array = np.ones((2, 2), dtype = 'int')
print(f"Ones array  = \n{ones_array}")

array_with_arrange = np.arange(0, 12, 3)
print(f"array_with_arrange  = \n{array_with_arrange}")

print(f"array_with_reshape  = \n{np.arange(0,12).reshape(2,6)}")

print(f"array_with_linespace  = \n{np.linspace(0,10,5)}")

Complex array  = 
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Ones array  = 
[[1 1]
 [1 1]]
array_with_arrange  = 
[0 3 6 9]
array_with_reshape  = 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
array_with_linespace  = 
[ 0.   2.5  5.   7.5 10. ]


#### Basic Operations
    - Add, mul, sub, div did on all element if 2 matrix then added like "a[0][0] + b[0][0]", "a[0][1] + b[0][1]"
      - a = np.arrange(0,4)
      - a =+ 4 will add 4 in all elements
    - other functions (universal function, generally called ufunc)
      - np.sin(b)
      - np.sqrt(b)
      - np.log(a) 
      - np.dot(A,B)  or alternatively A.dot(B)   # matrix product
      - np.dot(B,A)   # this will do matrix of B and A different from np.dot(A,B)
    - Aggregate functions perform an operation on a set of values
      - a.sum(), a.min(), a.max(), a.mean(), a.std()

In [141]:
a = np.arange(0,4).reshape(2,2)
b = np.arange(2,6).reshape(2,2)
print(f"a = {a},\nb = {b},\nsum = \n{a+b}")

print(f"sin_multiplication = \n{a*np.sin(b)}")

a = [[0 1]
 [2 3]],
b = [[2 3]
 [4 5]],
sum = 
[[2 4]
 [6 8]]
sin_multiplication = 
[[ 0.          0.14112001]
 [-1.51360499 -2.87677282]]


#### access elemt in array, indexing,slicing,iterating
    - access using [row index, column index]
    - short using array[start_index:End_index:gap]
      - example a[1:5:2]
      - other valids a[::2], a[:5:2], a[:5:]  
      - For 2 dimenstional use A[0:2, 0:2] 
    - Apply loop using "for a in array" : a is variable name.
      - For 2 dimensional it scans raw by raw
      - if want to iterate all element use "for item in A.flat"
    - np.apply_along_axis(np.mean, axis=0, arr=A)   # axis 0 is for row and axis 1 is for column

In [142]:
a = np.arange(0,12).reshape(3,4)
print(a)
print(f"a[0][2] = {a[0][2]}")

print(f"slice = \n{a[1:3,0:4:2]}")

print("iterating array = ")
for row in a:
    print(row, end = ', ')

print(f"\napply along row = {np.apply_along_axis(np.mean, axis=0, arr=a)}")

print(f"apply along column = {np.apply_along_axis(np.mean, axis=1, arr=a)}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[0][2] = 2
slice = 
[[ 4  6]
 [ 8 10]]
iterating array = 
[0 1 2 3], [4 5 6 7], [ 8  9 10 11], 
apply along row = [4. 5. 6. 7.]
apply along column = [1.5 5.5 9.5]


#### condition and boolean
    - check condition using <, >
      - A < 0.5 returns array with true false
      - sort array using A[A<0.5]
    - Shape change. 
      -  A = a.reshape(3, 4)      #reshape() function returns a new array and can therefore create new objects
      -  a.shape = (3,4)          # will not crete new object
      -  a = a.ravel() or a.shape = (A.size)  # will convert to one dimentional array
      -  A.transpose()          # to transpose an array

In [143]:
a = np.random.random((2,6))
print(f"Condition check a<0.5 = \n{a<0.5}")
filtered_array = a[a<0.5]
print(f"filtered_array = {filtered_array}")

A = a.reshape(3,4)
print("3*4 array = \n",A)

a = a.ravel()
print("1 dimentional array = ",a)

Condition check a<0.5 = 
[[ True False False False  True  True]
 [False False  True False  True  True]]
filtered_array = [0.26915143 0.00277312 0.16263046 0.40914628 0.20823554 0.32564995]
3*4 array = 
 [[0.26915143 0.9872835  0.96090749 0.83658245]
 [0.00277312 0.16263046 0.53502055 0.5355382 ]
 [0.40914628 0.62002241 0.20823554 0.32564995]]
1 dimentional array =  [0.26915143 0.9872835  0.96090749 0.83658245 0.00277312 0.16263046
 0.53502055 0.5355382  0.40914628 0.62002241 0.20823554 0.32564995]


#### Array Manupulation
    - Join/split array 
      - use 'vstack'(vertical stack) or 'hstack' (horizonal) for 2 dimentional array
        - need to pass only one argument so 2 brackets will be used np.hstack((a,b))
      - use 'column_stack'(vertical stack) or 'row_stack' (horizonal) for 1 dimentional array
        - example 'np.column_stack((a, b, c))'
      - use 'hsplit()' or 'vsplit()' to split an array
      - use noraml 'split' function
        - np.split(A,[1,3],axis=1)    # axis =1 means indexes by column
        - for row use axis = 0
        - [1,3] denots first of which will include the first column, the second will include the second and the third column, and the third will include the last column,
        - here it menas first array will be till index 1 so include only 1
        - 3 denotes second will include index from 1 to upto 3 means indexes 1,2
        - last includes the remaining

In [144]:
a = np.arange(0,4).reshape(2,2)
b = np.arange(4,8).reshape(2,2)
stack_by_row = np.vstack((a,b))
stack_by_column = np.hstack([a,b])

print(f"stack_by_row = \n{stack_by_row}")
print(f"stack_by_column = \n{stack_by_column}")

[A,B] = np.hsplit(stack_by_column,2)
print(f"A = {A}")
print(f"B = {B}")

print(np.split(stack_by_column,[2,3],axis=1))

stack_by_row = 
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
stack_by_column = 
[[0 1 4 5]
 [2 3 6 7]]
A = [[0 1]
 [2 3]]
B = [[4 5]
 [6 7]]
[array([[0, 1],
       [2, 3]]), array([[4],
       [6]]), array([[5],
       [7]])]


#### general concept
    - when you are manipulating an array, you can return a copy or a view of the array. None of the NumPy assignments produces copies of arrays, nor any element contained in them.
    - a * b (one dimentional array) is equal to
      - for (i = 0; i < rows; i++){                
            c[i] = a[i]*b[i];                
        }   
    - For 2 dimentional
      - for( i=0; i < rows; i++){                
            for(j=0; j < columns; j++){                
                c[i][j] = a[i][j]*b[i][j];                
                }                
            }  
    - Broadcasting allows an operator or a function to act on two or more arrays even if these arrays do not have the same shape
      - Example addition of 2 array (3,2,1) and (3,1,2)

In [145]:
m = np.arange(6).reshape(3, 1, 2)
n = np.arange(6).reshape(3, 2, 1)

print(f"m = {m}")
print(f"n = {n}")
print(f"SUM = {m+n}")

m = [[[0 1]]

 [[2 3]]

 [[4 5]]]
n = [[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]
SUM = [[[ 0  1]
  [ 1  2]]

 [[ 4  5]
  [ 5  6]]

 [[ 8  9]
  [ 9 10]]]


#### Structured array
    - Data type             Specifies type using dtype
        bytes                     b1              
        int                       i1, i2, i4, i8              
        unsigned ints             u1, u2, u4, u8              
        floats                    f2, f4, f8              
        complex                   c8, c16              
        fixed length strings      a<n>   
    - Example : structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3, 2-2j), (3, 'Third', 0.8, 1+3j)],dtype=('i2, a6, f4, c8'))
    - data type explicitly by specifying int8, uint8, float16, complex64 is also possible
    - structured[1]             # will call first row
    - Specify the names using
      - dtype=[('id','i2'),('position','a6'),('value','f4'),('complex','c8')]
      - call 'structured.dtype.names' to get names
      - 'structured['position']' will call detail of position in array

In [146]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3, 2-2j), (3, 'Third', 0.8, 1+3j)],dtype=('i2, S6, f4, c8'))
print(f"structured_array = {structured}")
structured

structured_array = [(1, b'First', 0.5, 1.+2.j) (2, b'Second', 1.3, 2.-2.j)
 (3, b'Third', 0.8, 1.+3.j)]


array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [147]:
print(f"one row = {structured[0]}")
#print(f"second row = {structured['f1']}")

# sepcifying names
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3, 2-2j), (3, 'Third', 0.8, 1+3j)],dtype=[('id','i2'),('position','S6'),('value','f4'),('complex','c8')])
structured

one row = (1, b'First', 0.5, 1.+2.j)


array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [148]:
print(structured.dtype.names)
structured['position']

('id', 'position', 'value', 'complex')


array([b'First', b'Second', b'Third'], dtype='|S6')